/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.ChatLink;
import edu.java.scrapper.domain.jooq.tables.Link;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CHAT_LINK_LINK_ID_INDEX = Internal.createIndex(DSL.name("CHAT_LINK_LINK_ID_INDEX"), ChatLink.CHAT_LINK, new OrderField[] { ChatLink.CHAT_LINK.LINK_ID }, false);
    public static final Index LINK_URL_INDEX = Internal.createIndex(DSL.name("LINK_URL_INDEX"), Link.LINK, new OrderField[] { Link.LINK.URL }, false);
}
